Repository Nekompiliuoja/Champions-of-the-Realm, pull requests merged in 2023-04, with the labels that each got.

#46 COTR-62 Add export presets
  .gitignore
  export_presets.cfg
Labels: enhancement

#47 COTR-64 enemy spawner
  .vs/COTR/DesignTimeBuild/.dtbcache.v2
  .vs/COTR/FileContentIndex/137cfa83-7063-44a0-a024-13ec729bebae.vsidx
  .vs/COTR/FileContentIndex/b018e50a-cc7d-465e-b1fd-81cc435bf2f6.vsidx
  .vs/COTR/FileContentIndex/d8953e90-572e-43ef-8dca-e98f90980f93.vsidx
  .vs/COTR/FileContentIndex/fa561501-d7f5-4dcc-96d6-ffcac946dc34.vsidx
  .vs/COTR/v17/.futdcache.v2
  .vs/COTR/v17/.suo
  .vs/ProjectEvaluation/cotr.metadata.v5.2
  .vs/ProjectEvaluation/cotr.projects.v5.2
  Scenes/Globals/Globals.cs
  Scenes/Maps/Main/Main.tscn
  Scenes/Maps/Main/Map.cs
  Scenes/Utility/EnemySpawner.cs
  Scenes/Utility/EnemySpawner.tscn
  Scenes/Utility/SpawnInfo.cs
  Scenes/Utility/SpawnInfo.tres
Labels: enhancement

#49 COTR-63 Updated the main menu design
  Scenes/UI/Menus/Main/MainMenu.tscn
  Sprites/UI/MainMenu/Menus_Detailed.png
  project.godot
Labels: enhancement

#53 COTR-60 implement enemy animation
  .vs/COTR/DesignTimeBuild/.dtbcache.v2
  .vs/COTR/FileContentIndex/137cfa83-7063-44a0-a024-13ec729bebae.vsidx
  .vs/COTR/FileContentIndex/b018e50a-cc7d-465e-b1fd-81cc435bf2f6.vsidx
  .vs/COTR/FileContentIndex/d8953e90-572e-43ef-8dca-e98f90980f93.vsidx
  .vs/COTR/FileContentIndex/fa561501-d7f5-4dcc-96d6-ffcac946dc34.vsidx
  .vs/COTR/v17/.futdcache.v2
  .vs/COTR/v17/.suo
  .vs/ProjectEvaluation/cotr.metadata.v5.1
  .vs/ProjectEvaluation/cotr.projects.v5.1
  Scenes/Actors/Troops/Infantry.cs
  Scenes/Actors/Troops/Infantry/Footman.cs
  Scenes/Actors/Troops/Infantry/FootmanEnemy.tscn
  Scenes/UI/Menus/Main/MainMenu.tscn
Labels: enhancement

#55 COTR-23 Implemented music
  .gitignore
  Scenes/Maps/Main/Main.tscn
  Scenes/UI/Menus/Main/MainMenu.tscn
  Sounds/Music/IdleMusic.mp3
  Sounds/Music/IdleMusic.mp3.import
  Sounds/Music/InActionMusic.mp3
  Sounds/Music/InActionMusic.mp3.import
  Sounds/Music/MainMenuMusic.mp3
  Sounds/Music/MainMenuMusic.mp3.import
Labels: enhancement

#52 COTR-68 Implemented basic Loot functionality
  .gitignore
  Scenes/Globals/IPoolable.cs
  Scenes/Globals/ObjectPool.cs
  Scenes/Maps/Main/Main.tscn
  Scenes/Maps/Main/Map.cs
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/Utility/Loot/Coins/BronzeCoin.tscn
  Scenes/Utility/Loot/Coins/Coin.cs
  Scenes/Utility/Loot/Coins/Coin.tscn
  Scenes/Utility/Loot/Coins/GoldenCoin.tscn
  Scenes/Utility/Loot/Coins/SilverCoin.tscn
  Scenes/Utility/Loot/LootManager.cs
  Scenes/Utility/Loot/LootManager.tscn
  Sprites/Loot/Coins/BronzeCoin.png
  Sprites/Loot/Coins/GoldenCoin.png
  Sprites/Loot/Coins/SilverCoin.png
Labels: enhancement

#56 COTR-66 Implemented basic loot drop functionality
  Scenes/Actors/Actor.cs
  Scenes/Actors/Troops/Infantry.cs
  Scenes/Actors/Troops/Infantry/Footman.cs
  Scenes/Actors/Troops/Troop.cs
  Scenes/Globals/Globals.cs
  Scenes/Maps/Main/Main.tscn
  Scenes/Maps/Main/Map.cs
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/Utility/Loot/Coins/Coin.cs
  Scenes/Utility/Loot/LootManager.cs
Labels: enhancement

#58 COTR-73 problems with handle hit and die methods
  .vs/COTR/DesignTimeBuild/.dtbcache.v2
  .vs/COTR/v17/.suo
  Scenes/Actors/Actor.cs
  Scenes/Actors/Player/Player.cs
  Scenes/Actors/Player/Player.tscn
  Scenes/Actors/Troops/Infantry.cs
  Scenes/Actors/Troops/Infantry/FootmanEnemy.tscn
  Scenes/Actors/Troops/Troop.cs
  Scenes/Maps/Main/Main.tscn
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/Utility/Loot/Coins/BronzeCoin.tscn
  Scenes/Utility/Loot/Coins/Coin.cs
  Scenes/Utility/Loot/Coins/Coin.tscn
  Scenes/Utility/Loot/Coins/GoldenCoin.tscn
  Scenes/Utility/Loot/LootManager.cs
  Sounds/SFX/Utility/Loot/coins.mp3
Labels: enhancement

#54 COTR-65 further GUI improvements
  .vs/COTR/FileContentIndex/dff85e55-70db-43a8-a15d-591aadc4506d.vsidx
  .vs/ProjectEvaluation/cotr.metadata.v5.2
  .vs/ProjectEvaluation/cotr.projects.v5.2
  COTR.csproj.old
  Scenes/Actors/Player/Player.tscn
  Scenes/UI/HUD/GUI.cs
  Scenes/UI/HUD/HUD.tscn
  Sprites/UI/Currency/GoldenCoin.png
Labels: enhancement

#60 COTR-58 trails
  .vs/COTR/FileContentIndex/03a89438-cb9b-483e-99cd-42810e44964c.vsidx
  .vs/COTR/FileContentIndex/2f650ee9-73f6-4f64-b595-063311eb9d94.vsidx
  .vs/COTR/FileContentIndex/a44a29af-75e7-44e7-ac35-e06b7924ce80.vsidx
  Material/Particles/Blood/Blood.tscn
  Particles/Trails/WalkingTrail.tscn
  Scenes/Actors/Player/Player.cs
  Scenes/Actors/Player/Player.tscn
Labels: enhancement

#61 COTR-89 Implemented knockback
  .vs/COTR/FileContentIndex/03a89438-cb9b-483e-99cd-42810e44964c.vsidx
  .vs/COTR/FileContentIndex/2f650ee9-73f6-4f64-b595-063311eb9d94.vsidx
  .vs/COTR/FileContentIndex/a44a29af-75e7-44e7-ac35-e06b7924ce80.vsidx
  .vs/COTR/FileContentIndex/dff85e55-70db-43a8-a15d-591aadc4506d.vsidx
  .vs/COTR/v17/.futdcache.v2
  .vs/COTR/v17/.suo
  .vs/ProjectEvaluation/cotr.metadata.v5.1
  .vs/ProjectEvaluation/cotr.projects.v5.1
  Scenes/Actors/Actor.cs
  Scenes/Actors/Player/Player.tscn
  Scenes/Actors/Troops/Infantry/FootmanEnemy.tscn
  Scenes/Actors/Troops/Infantry/Weapon.cs
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/Weapons/Melee/Melee.cs
  Scenes/Weapons/Melee/Melee.tscn
Labels: enhancement

#64 COTR-94 Attack using a mouse
  Scenes/Actors/Player/Player.cs
  Scenes/Actors/Player/Player.tscn
  Scenes/Maps/Main/Main.tscn
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/Weapons/Melee/Melee.tscn
Labels: enhancement

#68 COTR-80 Automatically set enemy target on spawn
  Scenes/Actors/Troops/MeleeAI.cs
  Scenes/Actors/Troops/MeleeAI.tscn
Labels: bug

#70 Repository cleanup
  .gitignore
  .vs/COTR/DesignTimeBuild/.dtbcache.v2
  .vs/COTR/FileContentIndex/read.lock
  .vs/COTR/v17/.futdcache.v2
  .vs/COTR/v17/.suo
  .vs/ProjectEvaluation/cotr.metadata.v5.1
  .vs/ProjectEvaluation/cotr.metadata.v5.2
  .vs/ProjectEvaluation/cotr.projects.v5.1
  .vs/ProjectEvaluation/cotr.projects.v5.2
  COTR.csproj.old
Labels: bug

#71 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#69 COTR-82 Spawn infinite enemies with increasing difficulty
  Scenes/Maps/Main/Map.cs
  Scenes/Utility/EnemySpawner.cs
  Scenes/Utility/EnemySpawner.tscn
  Scenes/Utility/SpawnInfo.cs
Labels: enhancement

#72 COTR-75 Made enemies spawn within radius
  Scenes/Actors/Actor.cs
  Scenes/Actors/Player/WeaponsManager.cs
  Scenes/Globals/Globals.cs
  Scenes/Maps/Main/Map.cs
  Scenes/UI/HUD/GUI.cs
  Scenes/UI/Menus/Loading/LoadingScreen.cs
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/UI/Menus/Settings/Settings.cs
  Scenes/UI/Menus/Shop/Shop.cs
  Scenes/Utility/EnemySpawner.cs
  Scenes/Utility/EnemySpawner.tscn
Labels: enhancement

#74 COTR-83 Enemies can get stuck behind obstacles
  Scenes/Actors/Troops/Infantry.cs
  Scenes/Actors/Troops/Infantry.tscn
  Scenes/Actors/Troops/Infantry/FootmanEnemy.tscn
  Scenes/Actors/Troops/MeleeAI.cs
  Scenes/Maps/Main/Main.tscn
  Scenes/Maps/Main/Map.cs
  Scenes/UI/Menus/Main/MainMenu.tscn
  Sprites/Maps/Environment/Tilesets/LiquidMerged.png
  project.godot
Labels: enhancement
