Repository Nekompiliuoja/Champions-of-the-Realm, pull requests merged in 2023-05, with the labels that each got.

#73 Minor cleanup for all scripts
  COTR.csproj
  Material/Particles/Blood/Blood.cs
  Scenes/Actors/Actor.cs
  Scenes/Actors/Player/Player.cs
  Scenes/Actors/Player/WeaponsManager.cs
  Scenes/Actors/Stats.cs
  Scenes/Actors/Team.cs
  Scenes/Actors/Troops/Infantry.cs
  Scenes/Actors/Troops/Infantry/Footman.cs
  Scenes/Actors/Troops/Infantry/Weapon.cs
  Scenes/Actors/Troops/MeleeAI.cs
  Scenes/Actors/Troops/Troop.cs
  Scenes/Globals/Globals.cs
  Scenes/Globals/IPoolable.cs
  Scenes/Globals/ObjectPool.cs
  Scenes/Maps/Main/Map.cs
  Scenes/UI/CharacterMenu/LevelSystem.cs
  Scenes/UI/DamagePopup/DamagePopup.cs
  Scenes/UI/HUD/GUI.cs
  Scenes/UI/Menus/GameOver/GameOver.cs
  Scenes/UI/Menus/Loading/LoadingScreen.cs
  Scenes/UI/Menus/Main/MainMenu.cs
  Scenes/UI/Menus/Pause/PauseMenu.cs
  Scenes/UI/Menus/Settings/Settings.cs
  Scenes/UI/Menus/Shop/Shop.cs
  Scenes/UI/Menus/Shop/WeaponSlot.cs
  Scenes/Utility/EnemySpawner.cs
  Scenes/Utility/Loot/Coins/Coin.cs
  Scenes/Utility/Loot/LootManager.cs
  Scenes/Weapons/Melee/Melee.cs
Labels: good first issue

#80 COTR-87 Loading screen fixed
  Scenes/Actors/Player/Player.cs
  Scenes/Actors/Player/Player.tscn
  Scenes/Globals/Globals.cs
  Scenes/Maps/Main/Main.tscn
  Scenes/Maps/Main/Map.cs
  Scenes/UI/Menus/Loading/LoadingScreen.cs
  Scenes/UI/Menus/Loading/LoadingScreen.tscn
  Scenes/UI/Menus/Main/MainMenu.cs
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/UI/Menus/Pause/PauseMenu.cs
  Scenes/UI/Menus/Pause/PauseMenu.tscn
Labels: bug

#81 COTR-102 Player coins are not saved
  Scenes/Actors/Player/Player.cs
  Scenes/Actors/Player/Player.tscn
  Scenes/Actors/Troops/Infantry/FootmanEnemy.tscn
  Scenes/Actors/Troops/MeleeAI.cs
  Scenes/Globals/Globals.cs
  Scenes/Maps/Main/Main.tscn
  Scenes/Maps/Main/Map.cs
  Scenes/UI/HUD/HUD.tscn
  Scenes/UI/Menus/GameOver/GameOver.cs
  Scenes/UI/Menus/GameOver/GameOver.tscn
  Scenes/UI/Menus/Main/MainMenu.tscn
Labels: bug

#82 COTR-49 Added custom fonts
  Fonts/Arvo-Bold.ttf
  Fonts/Arvo-BoldItalic.ttf
  Fonts/Arvo-Italic.ttf
  Fonts/Arvo-Regular.ttf
  Fonts/BreeSerif-Regular.ttf
  Scenes/UI/HUD/HUD.tscn
  Scenes/UI/Menus/GameOver/GameOver.tscn
  Scenes/UI/Menus/Loading/LoadingScreen.tscn
  Scenes/UI/Menus/Main/MainMenu.tscn
  Scenes/UI/Menus/Pause/PauseMenu.tscn
  Scenes/UI/Menus/Settings/Settings.tscn
  Scenes/UI/Menus/Shop/Shop.tscn
  Scenes/UI/Menus/Shop/WeaponSlot.tscn
Labels: enhancement
